### ISSUE TITLE
Update short summary

### ISSUE THREAD

**Issue by CsatiZoltan** [texstremists/Document-design#3]
Update the [main readme file](https://github.com/texstremists/Document-design/blob/master/README.md) with references to [this](https://github.com/texstremists/Document-design/commit/eaeb07a78ad0b55f1591d138f09787d34dae7d1b) and [that](https://github.com/texstremists/Document-design/commit/bd03e0b6466c1a901d09e7f52fc6de2f0c6e1297) entries.

**Comment by sylph1o** [comment]
Done for the wiki. I will do it later for the README.
